server:
  port: 9093

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://yhocn.cn;DatabaseName=t763812834_20251118
    username: sa
    password: Lyh07910_001
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  mvc:
    view:
      suffix: .html
    static-path-pattern: /**
  web:
    resources:
      static-locations: file:${web.upload-path},classpath:/templates/,classpath:/static/

  thymeleaf:
    cache: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

web:
  upload-path: ./upload/
  resources:
    static-locations: classpath:/static/,file:${pdf.upload.path}

pdf:
  upload:
    path: /data/uploads/pdf/
    access:
      base-url: /pdf/